[book]
authors = ["sgoudham"]
language = "en"
src = "src"
title = "Catppuccin's mdBook"

[output.html]
default-theme = "latte"
preferred-dark-theme = "mocha"
additional-css = [
  "./theme/catppuccin.css"
]
no-section-label = true
git-repository-url = "https://github.com/catppuccin/mdBook"
# git-repository-icon = "fa-github"
edit-url-template = "https://github.com/catppuccin/mdBook/edit/main/example/{path}"
cname = "mdbook.catppuccin.com"
